#!/usr/bin/env python3

import json
import locale
import sys


def load_data(filename):
  """Loads the contents of filename as a JSON file."""
  with open(filename) as json_file:
    data = json.load(json_file)
  return data


def format_car(car):
  """Given a car dictionary, returns a nicely formatted name."""
  return "{} {} ({})".format(
      car["car_make"], car["car_model"], car["car_year"])


def process_data(data):
  """Analyzes the data, looking for maximums.

  Returns a list of lines that summarize the information.
  """
  max_revenue = {"revenue": 0}
  max_sales = {"total_sales": 0}
  years = {}
  for item in data:
    # Calculate the revenue generated by this model (price * total_sales)
    # We need to convert the price from "$1234.56" to 1234.56
    item_price = locale.atof(item["price"].strip("$"))
    item_revenue = item["total_sales"] * item_price
    if item_revenue > max_revenue["revenue"]:
      item["revenue"] = item_revenue
      max_revenue = item
    if item["total_sales"] > max_sales["total_sales"]:
      max_sales = item
    
    year = item["car"]["car_year"]
    if year not in years:
        years[year] = item["total_sales"]
    else:
        years[year] += item["total_sales"]
    
    
    
  # print(max_revenue)
  # print(max_sales)
  # print(years)
  # print(max(years, key=years.get))
  summary = [
    "The {} generated the most revenue: ${} <br/>".format(
      format_car(max_revenue["car"]), max_revenue["revenue"]),
    "The {} had the most sales: {} <br/>".format(
      format_car(max_sales["car"]), max_sales["total_sales"]),
    "The most popular year was {} with {} sales. <br/>".format(
      max(years, key=years.get), years[max(years, key=years.get)]),
  ]





  return summary


def cars_dict_to_table(car_data):
  """Turns the data in car_data into a list of lists."""
  table_data = [["ID", "Car", "Price", "Total Sales"]]
  for item in car_data:
    table_data.append([item["id"], format_car(item["car"]), item["price"], item["total_sales"]])
  return table_data


def main(argv):
  """Process the JSON data and generate a full report out of it."""
  data = load_data("car_sales.json")
  summary = process_data(data)
  print(summary)
  
  
  # TODO: turn this into a PDF report
  import reports
  
  filename = '/tmp/cars.pdf'
  title = "Sales summary for last month"
  additional_info = ''.join(summary)
  table_data = cars_dict_to_table(data)
  
  reports.generate(filename, title, additional_info, table_data)

  # TODO: send the PDF report as an email attachment
  import emails
  sender = "automation@example.com"
  recipient = "student-04-5c525e579b5b@example.com"
  subject = "Sales summary for last month"
  body = 'The Mercedes-Benz E-Class (2009) generated the most revenue: $22749529.02\nThe Acura Integra (1995) had the most sales: 1192\nThe most popular year was 2007 with 21534 sales'
  attachment_path = '/tmp/cars.pdf'
  
  message = emails.generate(sender, recipient, subject, body, attachment_path)

  emails.send(message)

if __name__ == "__main__":
  main(sys.argv)

